---
title: "Pediatric Multivariate Covariate Simulation"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Pediatric_Cov_Sim}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message =FALSE,
  warning =FALSE,
  fig.width = 7,
  comment = "#>",
  dev.args = list(png = list(type = "cairo"))
)
library(coveffectsplot)
library(gamlss.dist)
library(tidyr)
library(dplyr)
library(ggplot2)
library(mrgsolve)
theme_set(theme_bw())

```

```{r pedpkmodel, collapse=TRUE }
pedpkmodelcov <- '
$PARAM
CL = 4, V=10 , KA=0.5
CLWT = 0.75,VWT = 1,
WT=16, SEX=0, AGE=4   

$CMT GUT CENT
$MAIN
double CLi = CL *
    pow((WT/22.5), CLWT)*exp(ETA(1)); 
double Vi = V *
    pow((WT/22.5), VWT)*exp(ETA(2));  

double KAi = KA;
double Keli = CLi/Vi    ;

$OMEGA
0.3 
0.01 0.3 

$ODE
dxdt_GUT  = -KAi*GUT;
dxdt_CENT =  KAi*GUT-Keli*CENT;

$TABLE
double CP   = CENT/ Vi;
$CAPTURE CP KAi CLi Vi 
'
pedmodsim <- mcode("pedpkmodelcov", pedpkmodelcov)

idata <- tibble(
  ID = 1:1000,
  WT = c(rep(15.87824,500),rep(16.31677,500)),
  AGE = 6,
  SEX = c(rep(0,500),rep(1,500))
)
ev1 <- ev(time = 0, amt = 100, cmt = 1)
data.dose <- ev(ev1)
data.dose <- as.data.frame(data.dose)
data.all <- merge(idata, data.dose)

outputsim <- pedmodsim %>%
  data_set(data.all) %>%
  carry.out(WT, AGE, SEX, CLi) %>%
  mrgsim(end = 24, delta = 0.25)
outputsim <- as.data.frame(outputsim)
outputsim <- outputsim %>%
  arrange(ID, time)
outputsim$SEX <- as.factor(outputsim$SEX)

set.seed(678549)
p1 <- ggplot(data = outputsim,
       aes(time, CP, group = ID)) +
  geom_line(alpha = 0.2, size = 0.1) +
  facet_grid(AGE ~ WT+SEX,
             labeller = label_both) +
  scale_y_log10() +
  labs(y = expression(Log[10]~~Plasma~~Concentrations), color = "Sex", x = "Time (h)")
p1

NCATYPICAL <- outputsim %>%
  group_by(ID, AGE, WT, SEX) %>%
  summarise (
    Cmax = max(CP, na.rm = TRUE),
    AUC = sum(diff(time) * na.omit(lead(CP) + CP)) / 2
  ) %>%
  gather(paramname, paramvalue, Cmax,  AUC)

NCATYPICALREF <- NCATYPICAL%>%
  group_by (paramname,SEX) %>%
  mutate(medparam = median(paramvalue),
         paramvalue = paramvalue / medparam) 

 ggplot(NCATYPICALREF,
       aes(x=paramvalue))+
      facet_grid(paramname~SEX,scales="free_y")+
        geom_density()+
  theme_bw()+
  theme(legend.position = "none")+
  labs(x="Standardized NCA parameters",y="")+
  scale_x_log10()+
  coord_cartesian(expand = FALSE)
  BSVRANGES<- NCATYPICALREF %>%
      group_by(SEX) %>%
  summarize(
    P05 = quantile(paramvalue, 0.05),
    P25 = quantile(paramvalue, 0.25),
    P50 = quantile(paramvalue, 0.5),
    P75 = quantile(paramvalue, 0.75),
    P95 = quantile(paramvalue, 0.95)
  )
BSVRANGES

```

```{r simcovariate, collapse=TRUE }
wtage <- read.csv (url("https://www.cdc.gov/growthcharts/data/zscore/wtage.csv"))
wtage<-  wtage[wtage$Agemos<=6*12,]

nweightsperage <- 50
simwtageoutput <- data.frame(matrix(NA, nrow = nrow(wtage),ncol = nweightsperage))
names(simwtageoutput) <- paste0("Var", 1:nweightsperage)

for (i in 1:nrow(wtage)) {#
  simpoints <- gamlss.dist::rBCCG(nweightsperage,
                                  mu = wtage[i,"M"],
                                  sigma =  wtage[i,"S"],
                                  nu = wtage[i,"L"])
simwtageoutput[i, ] <- simpoints
}
simwtageoutput$Agemos  <- wtage$Agemos
simwtageoutput$AgeY  <- wtage$Agemos/12
simwtageoutput$Sex <- wtage$Sex

simwtageoutput <- tidyr::gather(simwtageoutput,age,Weight,
                                paste0("Var", 1:nweightsperage))
simwtageoutput$age <- NULL
ggplot(simwtageoutput,aes(AgeY,Weight))+
  geom_point()+
  facet_grid(~Sex)

idata <- as.data.frame(simwtageoutput)
names(idata) <- c("Agemos","AGE","SEX","WT")
idata$SEX <-idata$SEX -1
ev1 <- ev(time=0,amt=100, cmt=1)
data.dose <- ev(ev1)
data.dose<-as.data.frame(data.dose)
data.all<-merge(idata,data.dose)
data.all$ID <- 1: nrow(data.all)
outcovcomb<- pedmodsim %>%
  data_set(data.all) %>%
  carry.out(WT,AGE,SEX,CLi) %>%
  zero_re() %>% 
  mrgsim(end=24, delta=1)
outcovcomb<-as.data.frame(outcovcomb)
outcovcomb <- outcovcomb %>% 
  arrange(ID,time,AGE,WT)
outcovcomb$SEX <- as.factor(outcovcomb$SEX )

ggplot(outcovcomb, aes(time,CP,col=factor(SEX),linetype=factor(SEX)) )+
  geom_line(aes(group=interaction(ID)),alpha=1,size=1.5)+
  facet_grid(cut(AGE,2)~ cut(WT,2),labeller = label_both)+
  labs(linetype="Sex",colour="Weight",caption ="Simulation without Uncertainty\nwithout BSV",
       x = "Time (h)", y="Plasma Concentrations")
```

    
```{r computenca, collapse=TRUE }  
  out.df.univariatecov <- as.data.frame(outcovcomb)
out.df.univariatecov <- out.df.univariatecov %>% 
  arrange(ID,time)

out.df.univariatecov.nca <- out.df.univariatecov %>% 
  group_by(ID,SEX,AGE,WT)%>% 
  summarise (Cmax = max(CP,na.rm = TRUE),
             AUC= sum(diff(time ) *na.omit(lead(CP) + CP)) / 2) 

out.df.univariatecov.nca.long <- out.df.univariatecov.nca %>% 
  gather(paramname,paramvalue,Cmax,AUC)

out.df.univariatecov.nca.long <- out.df.univariatecov.nca.long%>%
  group_by (paramname,SEX) %>%
  mutate(medparam = median(paramvalue),
         paramvalue = paramvalue / medparam) 

out.df.univariatecov.nca.long <- out.df.univariatecov.nca.long %>% 
  arrange(ID,SEX)

  ggplot(out.df.univariatecov.nca.long,
         aes( AGE,WT,col=factor(SEX)) )+
  geom_point(alpha=0.1,size=2)+
  facet_grid(paramname~SEX,labeller = label_value,
             scales="free_y")
  
    ggplot(out.df.univariatecov.nca.long,
         aes( WT,paramvalue,col=factor(SEX)) )+
  geom_point(alpha=0.1,size=2)+
  facet_grid(paramname~SEX,labeller = label_value,
             scales="free_y")
    
  ggplot(out.df.univariatecov.nca.long,
         aes( AGE,paramvalue,col=factor(SEX)) )+
  geom_point(alpha=0.1,size=2)+
  facet_grid(paramname~SEX,labeller = label_value,
             scales="free_y")
  

    
nca.summaries <- out.df.univariatecov.nca.long %>%
  mutate(WTCUT4 = cut(WT,4))%>%
  mutate(WTCUT2 = cut(WT,2))%>%
  mutate(AGECUT4 = cut(AGE,4))


```

